main/urls.py
from django.urls import path
from main.views import show_main, create_shoes_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, add_shoes_entry_ajax
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_shoes
from main.views import delete_shoes, create_shoes_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-shoes-entry/', create_shoes_entry, name='create_shoes_entry'),
    path('shop/', show_main, name='shop'),  # Mengarahkan ke show_main
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-shoes/<uuid:id>', edit_shoes, name='edit_shoes'),
    path('delete/<uuid:id>', delete_shoes, name='delete_shoes'),
    path('create-shoes-entry-ajax', add_shoes_entry_ajax, name='add_shoes_entry_ajax'),
    path('create-flutter/', create_shoes_flutter, name='create_shoes_flutter'),
]

sole_de_luxe/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<header class="bg-white shadow-lg fixed top-0 left-0 z-40 w-full py-6">
  <div class="flex justify-between items-center px-10">
      <!-- Menu di bagian kiri, hidden pada mobile, tampil pada layar >= md -->
      <div class="hidden md:flex space-x-12 text-lg">
          <a href="{% url 'main:shop' %}" class="text-black hover:text-gray-600 font-normal">HOME</a>
          <a href="{% url 'main:shop' %}#shoes_display_card" class="text-black hover:text-gray-600 font-normal">SHOP</a>

      </div>

      <!-- Title di Tengah -->
      <div class="flex-grow text-center">
          <span class="text-5xl font-[Sororite]">Sole de Luxe</span>
      </div>

      <!-- User options di bagian kanan, hidden pada mobile, tampil pada layar >= md -->
      <div class="hidden md:flex items-center space-x-8">
          {% if user.is_authenticated %}
              <span class="text-black font text-md">Welcome, {{ user.username }}</span>
              <a href="{% url 'main:logout' %}" class="bg-black hover:bg-gray-700 text-white font py-2 px-3 rounded transition-all duration-300 ease-in-out text-md">
                  Log Out
              </a>
          {% else %}
              <a href="{% url 'main:login' %}" class="bg-black hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded transition-all duration-300 ease-in-out text-lg">
                  Log In
              </a>
              <a href="{% url 'main:register' %}" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition duration-300">
                  Register
              </a>
          {% endif %}
      </div>

      <!-- Button untuk toggle menu di mobile -->
      <div class="md:hidden flex items-center">
          <button class="mobile-menu-button" aria-expanded="false" aria-controls="mobile-menu">
              <svg class="w-6 h-6 text-black" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                  <path d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
          </button>
      </div>
  </div>

  <!-- Mobile menu, tampil hanya pada mobile -->
  <div id="mobile-menu" class="mobile-menu hidden px-4 w-full">
      <div class="pt-2 pb-3 space-y-1 mx-auto">
        <span class="text-black font text-md">Welcome, {{ user.username }}</span>
          <div class="flex flex-col">
            
              <a href="{% url 'main:shop' %}" class="block text-left text-gray-600 hover:text-black hover:font-semibold transition duration-300 mb-1">HOME</a>
              <a href="{% url 'main:shop' %}#shoes_display_card" class="block text-left text-gray-600 hover:text-black hover:font-semibold transition duration-300 mb-1">SHOP</a>

              {% if user.is_authenticated %}
                  <a href="{% url 'main:logout' %}" class="block text-center bg-black hover:bg-[#615f5d] text-white font-bold py-3 px-6 rounded transition duration-300">Log Out</a>
              {% else %}
                  <a href="{% url 'main:login' %}" class="block text-center text-gray-600 hover:text-black transition duration-300 mb-2">Login</a>
                  <a href="{% url 'main:register' %}" class="block text-center bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded transition duration-300">Register</a>
              {% endif %}
          </div>
      </div>
  </div>

  <script>
      const btn = document.querySelector("button.mobile-menu-button");
      const menu = document.querySelector(".mobile-menu");

      btn.addEventListener("click", () => {
          const isHidden = menu.classList.toggle("hidden");
          btn.setAttribute("aria-expanded", !isHidden);
      });
  </script>
</header>